steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/line-discord-bot', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/line-discord-bot']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'line-discord-bot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/line-discord-bot'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-east1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DISCORD_WEBHOOK_URL=${_DISCORD_WEBHOOK_URL},LINE_CHANNEL_ACCESS_TOKEN=${_LINE_CHANNEL_ACCESS_TOKEN}'

images:
  - 'gcr.io/$PROJECT_ID/line-discord-bot'

substitutions:
  _DISCORD_WEBHOOK_URL: '你的DiscordWebhookURL'
  _LINE_CHANNEL_ACCESS_TOKEN: '你的LineChannelAccessToken'
