services:
  line-to-discord-service:
    build: .
    container_name: line-to-discord-service
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # redis:
  #   image: redis:alpine
  #   container_name: discord-redis
  #   restart: unless-stopped
