services:
  line-to-discord-service:
    build: .
    image: line-to-discord-service:latest # name:tag
    ports:
      - "443:8080" # LINE webhook 預設打 443，映射容器內部的 8080
    container_name: line-to-discord-service
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # redis:
  #   image: redis:alpine
  #   container_name: discord-redis
  #   restart: unless-stopped
